SET (CTEST_PROJECT_NAME "DIET")
SET (CTEST_NIGHTLY_START_TIME "22:00:00 MEST")
SET (CTEST_DROP_METHOD "http")
SET (CTEST_DROP_SITE "cdash.inria.fr")
SET (CTEST_DROP_LOCATION "/CDash/submit.php?project=DIET")
SET (CTEST_COMPRESS_SUBMISSION ON)
SET (CTEST_TRIGGER_SITE "")

