#
# Display a little summary
#

##############
MESSAGE( STATUS
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") 
MESSAGE( STATUS
  "XXXXXXXXXXXXXXXXXXXXXX  DIET DOC summary  XXXXXXXXXXXXXXXXXXXXXX") 
MESSAGE( STATUS
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") 
MESSAGE( STATUS "XXX - Install prefix: ${CMAKE_INSTALL_PREFIX}" ) 

##############
IF( PROGRAMMERSGUIDE )
  MESSAGE( STATUS "XXX   * ProgrammersGuide : ${PROGRAMMERSGUIDE} " ) 
ENDIF( PROGRAMMERSGUIDE )
IF( USERSMANUAL )
  MESSAGE( STATUS "XXX   * UserManual      : ${USERSMANUAL} " ) 
ENDIF( USERSMANUAL )
MESSAGE( STATUS  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") 
