#include <DIET_data.h>

#define EST_ALERT_FIRE (EST_USERDEFINED+1)
#define EST_ALERT_TEMPERATURE (EST_USERDEFINED+6)

#define EST_ENERGY_INSTANTCONSO (EST_USERDEFINED+2)
#define EST_PERFORMANCE_IAASFLOPS (EST_USERDEFINED+3)
#define EST_PERFORMANCE_AVGCPU (EST_USERDEFINED+4)

#define EST_IAAS_IMGPRESENT (EST_USERDEFINED+5)
