/*
 * MainFrame.java
 *
 * Created on 1 septembre 2006, 15:46
 */

/**
 *
 * @author  rbolze
 */
public class MainFrame extends javax.swing.JFrame {
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTestButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jOmniNamesTextField = new javax.swing.JTextField();
        jOmniNamesPortTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jTestButton.setText("TEST");
        jTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestButtonActionPerformed(evt);
            }
        });

        getContentPane().add(jTestButton, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("OmniNames");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel2, gridBagConstraints);

        jPanel3.add(jPanel2);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jOmniNamesTextField.setPreferredSize(new java.awt.Dimension(150, 19));
        jPanel1.add(jOmniNamesTextField, new java.awt.GridBagConstraints());

        jOmniNamesPortTextField.setPreferredSize(new java.awt.Dimension(150, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jOmniNamesPortTextField, gridBagConstraints);

        jPanel3.add(jPanel1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-262)/2, (screenSize.height-104)/2, 262, 104);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestButtonActionPerformed
        java.util.Properties props = new java.util.Properties();
        String omniNamesHost =jOmniNamesTextField.getText();
        String omniNamesPort =jOmniNamesPortTextField.getText();        
        props.put("org.omg.CORBA.ORBInitialHost", omniNamesHost);
        props.put("org.omg.CORBA.ORBInitialPort", omniNamesPort);
        String [] args = {""};
        try{
            System.out.println("Try to connection  "+omniNamesHost+" on port "+omniNamesPort);
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, props);            
            String[] list = orb.list_initial_services();
            System.out.println("initial services :");
            for(int i=0;i<list.length;i++){
                System.out.println("  -"+list[i]);
            }
            orb.destroy();
	    System.out.println("### OK ####");
        }catch (Exception e) {
            System.err.println("FAILED : Cannot connect to "+omniNamesHost+" on port "+omniNamesPort);            
        }
    }//GEN-LAST:event_jTestButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //disable WARNING messages !!
        java.util.logging.Logger logger = java.util.logging.Logger.getLogger("");
        logger.setLevel(java.util.logging.Level.OFF) ;
        // end
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jOmniNamesPortTextField;
    private javax.swing.JTextField jOmniNamesTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jTestButton;
    // End of variables declaration//GEN-END:variables
    
}
