#include <DIET_data.h>

#define EST_ALERT (EST_USERDEFINED+1)

#define EST_ENERGY_INSTANT (EST_USERDEFINED+2)

#define EST_PERFORMANCE_AVGCPU (EST_USERDEFINED+3)

#define EST_IAAS_IMGPRESENT (EST_USERDEFINED+4)
