/****************************************************************************/
/* Configure file includes autogenerated acDIET_config.h                    */
/* without PACKAGE_* definitions (to avoid collision with other             */
/* PACKAGE_* defines (for example omniORB)                                  */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Frauenkron Peter (Peter.Frauenkron@gmail.com)                       */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $@Id$
 * $@Log$
 ****************************************************************************/

#ifndef __DIET_CONFIG_H__
#define __DIET_CONFIG_H__

#include <./acDIET_config.h>

#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION

#endif //DIET_CONFIG_H
