#
# Display a little summary
#

# Display a title line
function(disp )
  if (NOT DEFINED ARGV1)
    set(char "X")
  else (NOT DEFINED ARGV1)
    set(char ${ARGV1})
  endif (NOT DEFINED ARGV1)
  
  set(cmpt 0)
  set(resultStr "")
  
  if (DEFINED ARGV0)
    string(LENGTH ${ARGV0} len)
  else (DEFINED ARGV0)
    set(len 0)
  endif (DEFINED ARGV0)
  
  if (${len} GREATER 0)
    math(EXPR len "${len} + 4")
  endif(${len} GREATER 0)
  math(EXPR len "(76  - ${len})/2")
  
  while (${cmpt} LESS ${len})
    set(resultStr ${resultStr}${char})
    math(EXPR cmpt "${cmpt}+1")
  endwhile (${cmpt} LESS ${len})
  
  if (DEFINED ARGV0)
    string(LENGTH ${ARGV0} modulo)
    math(EXPR modulo "${modulo} % 2")
    if (${modulo} EQUAL 0)
      set(resultStr "${resultStr}  ${ARGV0}  ${resultStr}")
    else (${modulo} EQUAL 0)
      set(resultStr "${resultStr}  ${ARGV0}  ${resultStr}${char}")
    endif (${modulo} EQUAL 0)
  else (DEFINED ARGV0)
    set(resultStr "${resultStr}${resultStr}")
  endif (DEFINED ARGV0)
  message(STATUS ${resultStr})
endfunction(disp)

disp()
disp("DIET ${DIET_VERSION}")
disp("Configuration summary")
disp("${DIET_BUILD_VERSION}")
disp()

if (CYGWIN)
  message(STATUS "XXX System name Cygwin on Windows")
elseif (APPLE)
  message(STATUS "XXX System name Darwin")
elseif (LINUX)
  message(STATUS "XXX System name Linux")
elseif (AIX)
  message(STATUS "XXX System name Aix")
elseif (SUNOS)
  message(STATUS "XXX System name SunOS")
elseif (FREEBSD)
  message(STATUS "XXX System name FreeBSD")
endif (CYGWIN)

message(STATUS "XXX - Install prefix: ${CMAKE_INSTALL_PREFIX}")
message(STATUS "XXX - C compiler   : ${CMAKE_C_COMPILER}")
if (CMAKE_C_COMPILER_VERSION)
  message(STATUS "XXX    * version   : ${CMAKE_C_COMPILER_VERSION}")
endif (CMAKE_C_COMPILER_VERSION)
message(STATUS "XXX    * options   : ${CMAKE_C_FLAGS}")
message(STATUS "XXX - CXX compiler : ${CMAKE_CXX_COMPILER}")
if (CMAKE_CXX_COMPILER_VERSION)
  message(STATUS "XXX    *  version  : ${CMAKE_CXX_COMPILER_VERSION}")
endif (CMAKE_CXX_COMPILER_VERSION)
message(STATUS "XXX    *  options  : ${CMAKE_CXX_FLAGS}")

message(STATUS "XXX - OmniORB found: ${OMNIORB4_FOUND}")
if (OMNIORB4_FOUND)
  message(STATUS "XXX   * OmniORB version: ${OMNIORB4_VERSION}")
  message(STATUS "XXX   * OmniORB directory: ${OMNIORB4_DIR}")
  message(STATUS "XXX   * OmniORB includes: ${OMNIORB4_INCLUDE_DIR}")
  message(STATUS "XXX   * OmniORB libraries:")
  foreach (lib ${OMNIORB4_LIBRARIES})
    message(STATUS "XXX     - ${lib}")
  endforeach (lib)
endif (OMNIORB4_FOUND)

message(STATUS "XXX - General options: ")
if (DIET_BUILD_LIBRARIES)
  if (BUILD_SHARED_LIBS)
    message(STATUS "XXX   * Dynamics Libraries: ON ")
  else(BUILD_SHARED_LIBS)
    message(STATUS "XXX   * Static Libraries: ON ")
  endif (BUILD_SHARED_LIBS)
endif (DIET_BUILD_LIBRARIES)

message(STATUS "XXX   * Examples: ${DIET_BUILD_EXAMPLES} ")
if (DIET_BUILD_EXAMPLES AND DIET_BUILD_BLAS_EXAMPLES)
  message(STATUS "XXX   * BLAS Examples: ${DIET_BUILD_BLAS_EXAMPLES} ")
endif (DIET_BUILD_EXAMPLES AND DIET_BUILD_BLAS_EXAMPLES)

message(STATUS "XXX - Options set: ")
if (DIET_USE_ACKFILE)
  message(STATUS "XXX   * Acknowledgement file: ${DIET_USE_ACKFILE} ")
endif (DIET_USE_ACKFILE)
if (DIET_USE_ALT_BATCH)
  message(STATUS "XXX   * Batch: ${DIET_USE_ALT_BATCH} ")
endif (DIET_USE_ALT_BATCH)
if (DIET_USE_CCS)
  message(STATUS "XXX   * Client scheduling: ${DIET_USE_CCS} ")
endif (DIET_USE_CCS)
if (DIET_USE_CLOUD)
  message(STATUS "XXX   * Cloud: ${DIET_USE_CLOUD} ")
  message(STATUS "XXX     -- source directory: ${GSOAP_SRC_DIR}")
endif (DIET_USE_CLOUD)
if (DIET_USE_CORI)
  message(STATUS "XXX   * CORI: ${DIET_USE_CORI} ")
endif (DIET_USE_CORI)
if (DIET_USE_DAGDA)
  message(STATUS "XXX   * DAGDA: ${DIET_USE_DAGDA} ")
  message(STATUS "XXX     -- Progression API: ${DIET_TRANSFER_PROGRESSION} ")
  if (UUID_LIB)
    message(STATUS "XXX     -- uuid library: ${UUID_LIB}")
    message(STATUS "XXX     -- uuid include: ${UUID_INCLUDE_DIR}/uuid.h")
  endif (UUID_LIB)
  if (APPLE)
    message(STATUS "XXX     -- Use Mac OS X builtin uuid library")
  endif (APPLE)
endif (DIET_USE_DAGDA)
if (DIET_USE_DART)
  message(STATUS "XXX   * Dart: ${DIET_USE_DART} ")
endif (DIET_USE_DART)
if (DIET_USE_DYNAMICS)
  message(STATUS "XXX   * Dynamics: ${DIET_USE_DYNAMICS} ")
endif (DIET_USE_DYNAMICS)
if (DIET_USE_FD)
  message(STATUS "XXX   * FD: ${DIET_USE_FD} ")
endif (DIET_USE_FD)
if (DIET_USE_FAST)
  message(STATUS "XXX   * FAST: ${DIET_USE_FAST} ")
endif (DIET_USE_FAST)
if (DIET_USE_JXTA)
  message(STATUS "XXX   * JXTA: ${DIET_USE_JXTA} ")
endif (DIET_USE_JXTA)
if (DIET_USE_JUXMEM)
  message(STATUS "XXX   * JuxMem: ${DIET_USE_JUXMEM} ")
endif (DIET_USE_JUXMEM)
if (DIET_USE_LOG)
  message(STATUS "XXX   * LogService: ${DIET_USE_LOG} ")
  message(STATUS "XXX     -- LogService library: ${LOG_LIBRARY}")
  message(STATUS "XXX     -- LogService include: ${LOG_SRC_DIR}")
endif (DIET_USE_LOG)
if (DIET_WITH_STATISTICS)
  message(STATUS "XXX   * Statistics: ${DIET_WITH_STATISTICS} ")
endif (DIET_WITH_STATISTICS)
if (DIET_WITH_MULTI_MA)
  message(STATUS "XXX   * Multi-MA: ${DIET_WITH_MULTI_MA} ")
endif (DIET_WITH_MULTI_MA)
if (DIET_TAU_PROFILING)
  message(STATUS "XXX   * TAU profiling: ${DIET_TAU_PROFILING} ")
endif (DIET_TAU_PROFILING)
if (DIET_USE_WORKFLOW)
  message(STATUS "XXX   * Workflow: ${DIET_USE_WORKFLOW} ")
  message(STATUS "XXX     -- Xerces version: ${XERCES_VERSION_MAJOR}.${XERCES_VERSION_MINOR}.${XERCES_VERSION_REVISION}")
  message(STATUS "XXX     -- Xerces directory: ${XERCES_DIR} ")
  message(STATUS "XXX     -- Xerces includes: ${XERCES_INCLUDE_DIR}")
  message(STATUS "XXX     -- Xerces library: ${XERCES_LIBRARY}")
  message(STATUS "XXX     -- XQilla directory: ${XQILLA_DIR} ")
  message(STATUS "XXX     -- XQilla includes: ${XQILLA_INCLUDE_DIR}")
  message(STATUS "XXX     -- XQilla library: ${XQILLA_LIBRARY}")
endif (DIET_USE_WORKFLOW)
disp()
