/****************************************************************************/
/* DIET forwarder IDL description                                           */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Gael Le Mahec   (gael.le.mahec@ens-lyon.fr)                         */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$
 * $Log$
 * Revision 1.3  2010/07/20 14:31:46  glemahec
 * Forwarder robustness + bug corrections
 *
 * Revision 1.2  2010/07/14 23:45:31  bdepardo
 * Header corrections
 *
 * Revision 1.1  2010/07/12 15:54:10  glemahec
 * DIET 2.5 beta 1 - Forwarder IDL files
 ****************************************************************************/


#ifndef AGENTFWDR_IDL
#define AGENTFWDR_IDL

#include "Agent.idl"
#include "common_types.idl"

interface AgentFwdr : Agent {

};

interface AgentForwarder {
  long agentSubscribe(in string agentName, in string hostname,
                      in SeqCorbaProfileDesc_t services,
                      in string objName)
    raises(UnknownObject);
  long serverSubscribe(in string seDName,
                       in string hostname,
                       in SeqCorbaProfileDesc_t services,
                       in string objName)
    raises(UnknownObject);

  long childUnsubscribe(in unsigned long childID,
                        in SeqCorbaProfileDesc_t services,
                        in string objName)
    raises(UnknownObject);

  long childRemoveService(in unsigned long childID,
                          in corba_profile_desc_t profile,
                          in string objName)
    raises(UnknownObject);
  long addServices(in unsigned long myID,
                   in SeqCorbaProfileDesc_t services,
                   in string objName)
    raises(UnknownObject);

  oneway void getResponse(in corba_response_t resp,
                          in string objName);

  string getDataManager(in string objName)
    raises(UnknownObject);
};

#endif
