/****************************************************************************/
/* DIET forwarder IDL description                                           */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Gael Le Mahec   (gael.le.mahec@ens-lyon.fr)                         */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$
 * $Log$
 * Revision 1.3  2010/07/20 14:31:46  glemahec
 * Forwarder robustness + bug corrections
 *
 * Revision 1.2  2010/07/14 23:45:31  bdepardo
 * Header corrections
 *
 * Revision 1.1  2010/07/12 15:54:11  glemahec
 * DIET 2.5 beta 1 - Forwarder IDL files
 ****************************************************************************/


#ifndef CLTMANFWDR_IDL
#define CLTMANFWDR_IDL

#include "CltMan.idl"

interface CltManFwdr : CltMan {

};

interface CltManForwarder {
	long execNodeOnSed(in string node_id,
										 in string dag_id,
										 in string seDName,
										 in unsigned long reqID,
										 inout corba_estimation_t ev,
										 in string objName)
		raises(UnknownObject);

  long execNode(in string node_id,
								in string dag_id,
								in string objName)
		raises(UnknownObject);

  string release(in string dag_id,
								 in boolean successful,
								 in string objName)
		raises(UnknownObject);
};

#endif
