/**
 * @file CltMan.idl
 *
 * @brief  CLIENT Manager Interface (used in workflow support)
 *
 * @author Abdelkader Amar (Abdelkader.Amar@ens-lyon.fr)
 *
 * @section Licence
 *   |LICENCE|
 */

#ifndef _CLTMAN_IDL_
#define _CLTMAN_IDL_

#include "response.idl"

interface CltMan {

  exception DagNotFound {
    string dagId;
  };

  /**
   * Request node execution on a given SeD
   * @param node_id node identifier (string)
   * @param dag_id  dag identifier (string)
   * @param sed_ref the SeD CORBA object reference
   * @param reqID   the DIET request ID of the previous submit request
   * @param ev  the estimation vector (from previous submit request used to
   * choose the SeD) - this param is inout to avoid const as the pointer is
   * stored in the Node object
   */
  long
  execNodeOnSed(in string node_id,
                in string dag_id,
                in string seDName,
                in unsigned long reqID,
                inout corba_estimation_t ev);

  /**
   * Request node execution on the best SeD available
   * (delegates SeD choice to default scheduler)
   * @param node_id node identifier (string)
   * @param dag_id  dag identifier (string)
   */
  long
  execNode(in string node_id,
           in string dag_id);

  /**
   * Release the manager after dag execution is either completed or
   * cancelled
   * @param dag_id  dag identifier (string)
   * @param successful  true if dag execution was successful
   */
  string
  release(in string dag_id, in boolean successful);

  long ping();
};

#endif // _CLTMAN_IDL_
