/****************************************************************************/
/* CLIENT Manager Interface (used in workflow support)                     */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Abdelkader Amar (Abdelkader.Amar@ens-lyon.fr)                       */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$ 
 * $Log$
 * Revision 1.3  2008/06/01 09:20:37  rbolze
 * the remote method release now return a string which contains
 * feedback on the dag execution
 *
 * Revision 1.2  2008/04/15 14:20:19  bisnard
 * - Postpone sed mapping until wf node is executed
 *
 * Revision 1.1  2008/04/10 08:17:14  bisnard
 * New version of the MaDag where workflow node execution is triggered by the MaDag agent and done by a new CORBA object CltWfMgr located in the client
 *
 ****************************************************************************/

#ifndef _CLTMAN_IDL_
#define _CLTMAN_IDL_

#include "response.idl"
#include "SeD.idl"

interface CltMan {
  void
  execNodeOnSed(in string node_id, in string dag_id,
	  in SeD sed_ref);

  void
  execNode(in string node_id, in string dag_id);

  string
  release(in string dag_id);

  void 
  ping();
};

#endif // _CLTMAN_IDL_
