/****************************************************************************/
/* CLIENT listener for reordering                                           */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Abdelkader Amar (Abdelkader.Amar@ens-lyon.fr)                        */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$ 
 * $Log$
 * Revision 1.3  2006/11/28 15:10:18  aamar
 * Correct headers
 *
 ****************************************************************************/

#ifndef _CLTREOMAN_IDL_
#define _CLTREOMAN_IDL_

#include "response.idl"

interface CltReoMan {
  void
  remainingSched(in wf_node_sched_seq_t wf_sched);

  string
  getremainingDag();
};

#endif // _CLTREOMAN_IDL_
