/**
 * @file DagdaFwdr.idl
 *
 * @brief  DIET forwarder IDL description 
 *
 * @author  Gael Le Mahec (lemahec@clermont.in2p3.fr)
 *
 * @section Licence
 *   |LICENCE|
 */


#ifndef DAGDAFWDR_IDL
#define DAGDAFWDR_IDL

#include "Dagda.idl"

interface DagdaFwdr : Dagda {

};

interface DagdaForwarder {
  boolean lclIsDataPresent(in string dataID,
													 in string objName)
		raises(UnknownObject);
  boolean lvlIsDataPresent(in string dataID,
													 in string objName)
		raises(UnknownObject);
  boolean pfmIsDataPresent(in string dataID,
													 in string objName)
		raises(UnknownObject);

  void lclAddData(in string srcDagda, in corba_data_t data,
									in string objName)
    raises(Dagda::InvalidPathName, Dagda::ReadError, Dagda::WriteError,
					 Dagda::NotEnoughSpace, UnknownObject);
  void lvlAddData(in string srcDagda, in corba_data_t data,
									in string objName)
    raises(Dagda::InvalidPathName, Dagda::ReadError, Dagda::WriteError,
					 Dagda::NotEnoughSpace, UnknownObject);
  void pfmAddData(in string srcDagda, in corba_data_t data,
									in string objName)
    raises(Dagda::InvalidPathName, Dagda::ReadError, Dagda::WriteError,
					 Dagda::NotEnoughSpace, UnknownObject);

  void registerFile(in corba_data_t data, in string objName)
    raises(Dagda::InvalidPathName, Dagda::UnreachableFile,
					 UnknownObject);

  void lclAddContainerElt(in string containerID,
                          in string dataID,
                          in long index,
                          in long flag,
													in string objName)
    raises(Dagda::DataNotFound, UnknownObject);

  long lclGetContainerSize(in string containerID, in string objName)
		raises(UnknownObject);

  void lclGetContainerElts(in string containerID,
                           inout SeqString dataIDSeq,
                           inout SeqLong flagSeq,
                           in boolean ordered,
													 in string objName)
		raises(UnknownObject);

  void lclRemData(in string dataID, in string objName)
		raises(UnknownObject);
  void lvlRemData(in string dataID, in string objName)
		raises(UnknownObject);
  void pfmRemData(in string dataID, in string objName)
		raises(UnknownObject);

  void lclUpdateData(in string srcDagda, in corba_data_t data, in string objName)
		raises(UnknownObject);
  void lvlUpdateData(in string srcDagda, in corba_data_t data, in string objName)
		raises(UnknownObject);
  void pfmUpdateData(in string srcDagda, in corba_data_t data, in string objName)
		raises(UnknownObject);

  SeqCorbaDataDesc_t lclGetDataDescList(in string objName)
		raises(UnknownObject);
  SeqCorbaDataDesc_t lvlGetDataDescList(in string objName)
		raises(UnknownObject);
  SeqCorbaDataDesc_t pfmGetDataDescList(in string objName)
		raises(UnknownObject);

  corba_data_desc_t lclGetDataDesc(in string dataID,
																	 in string objName)
    raises(Dagda::DataNotFound, UnknownObject);
  corba_data_desc_t lvlGetDataDesc(in string dataID,
																	 in string objName)
    raises(Dagda::DataNotFound, UnknownObject);
  corba_data_desc_t pfmGetDataDesc(in string dataID,
																	 in string objName)
    raises(Dagda::DataNotFound, UnknownObject);

  oneway void lclReplicate(in string dataID, in long ruleTarget,
													 in string pattern, in boolean replace,
													 in string objName);
  oneway void lvlReplicate(in string dataID, in long ruleTarget,
													 in string pattern, in boolean replace,
													 in string objName);
  oneway void pfmReplicate(in string dataID, in long ruleTarget,
													 in string pattern, in boolean replace,
													 in string objName);

  string writeFile(in SeqChar data, in string basename, in boolean replace,
									 in string objName)
    raises(Dagda::InvalidPathName, Dagda::WriteError, Dagda::NotEnoughSpace,
					 UnknownObject);
		
  string sendFile(in corba_data_t data, in string destDagda,
									in string objName)
    raises(Dagda::InvalidPathName, Dagda::ReadError, Dagda::WriteError,
					 UnknownObject);
		
  string recordData(in SeqChar data, in corba_data_desc_t dataDesc,
										in boolean replace, in long offset,
										in string objName)
    raises(Dagda::NotEnoughSpace, UnknownObject);
		
  string sendData(in string ID, in string destDagda, in string objName)
    raises(Dagda::DataNotFound, UnknownObject);
		
  string sendContainer(in string ID, in string destDagda, in boolean sendElements,
											 in string objName)
    raises(Dagda::DataNotFound, UnknownObject);


  SeqString lvlGetDataManagers(in string dataID, in string objName)
		raises(UnknownObject);
  SeqString pfmGetDataManagers(in string dataID, in string objName)
		raises(UnknownObject);

  void subscribe(in string dagdaName, in string objName)
		raises(UnknownObject);
  void unsubscribe(in string dagdaName, in string objName)
		raises(UnknownObject);

  string getID(in string objName)
		raises(UnknownObject);

  void lockData(in string dataID, in string objName)
		raises(UnknownObject);
  void unlockData(in string dataID, in string objName)
		raises(UnknownObject);

  Dagda::dataStatus getDataStatus(in string dataID, in string objName)
		raises(UnknownObject);

  string getBestSource(in string destDagda, in string dataID, in string objName)
    raises(Dagda::DataNotFound, UnknownObject);

  void checkpointState(in string objName)
		raises(UnknownObject);

  void subscribeParent(in string parentID, in string objName)
		raises(UnknownObject);
  void unsubscribeParent(in string objName)
		raises(UnknownObject);
};

#endif
