/**
 * @file LocalAgentFwdr.idl
 *
 * @brief  DIET forwarder IDL description  
 *
 * @author  Gael Le Mahec   (gael.le.mahec@ens-lyon.fr)
 *
 * @section Licence
 *   |LICENSE|
 */


#ifndef LOCALAGENTFWDR_IDL
#define LOCALAGENTFWDR_IDL

#include "LocalAgent.idl"
#include "AgentFwdr.idl"

interface LocalAgentFwdr : LocalAgent {

};

interface LocalAgentForwarder : AgentForwarder {
  long bindParent(in string parentName,
                  in string objName)
    raises(UnknownObject);
  long disconnect(in string objName)
    raises(UnknownObject);
};

#endif
