/****************************************************************************/
/* DIET forwarder IDL description                                           */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Gael Le Mahec   (gael.le.mahec@ens-lyon.fr)                         */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$
 * $Log$
 * Revision 1.2  2010/07/14 23:45:31  bdepardo
 * Header corrections
 *
 * Revision 1.1  2010/07/12 15:54:11  glemahec
 * DIET 2.5 beta 1 - Forwarder IDL files
 ****************************************************************************/


#ifndef LOCMGRFWDR_IDL
#define LOCMGRFWDR_IDL

#include "LocMgr.idl"

interface LocMgrFwdr : LocMgr {

};

interface LocMgrForwarder {
	unsigned long locMgrSubscribe(in string me, in string hostName, in string objName);
  unsigned long dataMgrSubscribe(in string me, in string hostName, in string objName);
  void addDataRef(in corba_data_desc_t arg, in unsigned long cChildID, in string objName);
  void rmDataRefLocMgr(in string argID, in unsigned long cChildID, in string objName);
  oneway void updateDataRef(in corba_data_desc_t arg,
			    in unsigned long cChildID, in long upDown, in string objName);
  string whereDataSubtree(in string argID, in string objName);
  void updateDataProp(in string argID, in string objName);
  long rm_pdata(in string argID, in string objName);
};

#endif
