/**
 * @file LogComponent.idl
 *
 * @brief  Defines the componentside interfaces needed by the new LogService   
 *
 * @author  Georg Hoesch (hoesch@in.tum.de)
 *          Cyrille Pontivieux (cyrille.pontivieux@ens-lyon.fr)
 *
 * @section Licence
 *   |LICENSE|
 */
#ifndef _LOGCOMPONENT_IDL_
#define _LOGCOMPONENT_IDL_

#include "LogTypes.idl"

/* This file defines everything that is needed to attach a component to the
 * LogCentral.
 */

/**
 * Errorlevel constants for connectComponent
 */
// const short LS_OK = 0; defined in the LogTypes.idl
const short LS_COMPONENT_CONNECT_BADNAME = 1;
const short LS_COMPONENT_CONNECT_ALREADYEXISTS = 2;
const short LS_COMPONENT_CONNECT_BADCOMPONENTCONFIGURATOR = 3;
const short LS_COMPONENT_CONNECT_INTERNALERROR = 4;

const short LS_COMPONENT_DISCONNECT_NOTEXISTS = 1;

/**
 * defines functions that the component has to implement 
 * to allow dynamic configuration.
 */
interface ComponentConfigurator {
  /**
   * Set the component filter to the specified taglist. All tags
   * in the list have to be forwarded, all others not.
   */
  void
  setTagFilter(in tag_list_t tagList);

  /**
   * Add the specified taglist to the internal filter and merge them.
   */
  void
  addTagFilter(in tag_list_t tagList);

  /**
   * Remove all tags from the taglist from the internal filter. The
   * given tagList may contain tags that the internal filter does
   * not contain.
   */
  void
  removeTagFilter(in tag_list_t tagList);

  /**
   * Do nothing. Useful to be sure that the object is reachable
   */
  void
  test();
};

/**
 * defines the interface the core offers to components
 */
interface LogCentralComponent {
  /**
   * Do nothing but usefull to be sure that the object is reachable
   */
  void
  test();

  /**
   * Connect a component to the LogCentral. The component attaches with its
   * name, which must be unique (among all components) and its hostname (no
   * need to be unique). If the name is an empty string, a name is generated.
   * The return value indicates if the component could be connected.
   * If ALREADYEXISTS is returned, another component with the given name is
   * registered. In this case, the connection was not successful, and the tool
   * must connect with a diferent name before invoking other functions of the
   * LogCentralComponent interface.
   */
  short
  connectComponent(inout string componentName,
                   in string componentHostname,
                   in string message,
                   in string compConfiguratorName,
                   in log_time_t componentTime,
                   inout tag_list_t initialConfig);


  /**
   * Disconnect a connected component from the LogCentral.
   * No further messages should be sent after disconnection.
   * The componentConfigurator will no longer be used by the LogCentral after
   * this call. Returns NOTCONNECTED if the calling component was not
   * registered.
   */
  short
  disconnectComponent(in string componentName, in string message);


  /**
   * Send a buffer of log_msg_t to the LogCentral.
   */
  oneway void
  sendBuffer(in log_msg_buf_t buffer);


  /**
   * Get the hostname of a specified component.
   */
  string
  getHostnameOf(in string componentName);

  /**
   * To be called by a thread for saying that the component is still alive.
   * If the last ping is too old, the component is considered dead and
   * generate a disconnect message (OUT).
   */
  oneway void
  ping(in string componentName);

  /**
   * To be called by a thread for clock synchronisation.
   */
  oneway void
  synchronize(in string componentName, in log_time_t componentTime);
};

#endif
