/**
 * @file LogComponentFwdr.idl
 *
 * @brief  DIET forwarder IDL description   
 *
 * @author  Gael Le Mahec   (gael.le.mahec@ens-lyon.fr)
 *
 * @section Licence
 *   |LICENSE|
 */


#ifndef LOGCOMPONENTFWDR_IDL
#define LOGCOMPONENTFWDR_IDL

#include "LogComponent.idl"
#include "common_types.idl"

interface ComponentConfiguratorFwdr : ComponentConfigurator {

};

interface LogCentralComponentFwdr : LogCentralComponent {

};

interface ComponentConfiguratorForwader {
  void setTagFilter(in tag_list_t tagList, in string objName)
		raises(UnknownObject);

  void addTagFilter(in tag_list_t tagList, in string objName)
		raises(UnknownObject);

  void removeTagFilter(in tag_list_t tagList, in string objName)
		raises(UnknownObject);

  void test(in string objName)
		raises(UnknownObject);
};


interface LogCentralComponentForwarder {
  void test(in string objName);

  short connectComponent(inout string componentName,
												 in string componentHostname,
												 in string message,
												 in string compConfiguratorName,
												 in log_time_t componentTime,
												 inout tag_list_t initialConfig,
												 in string objName)
		raises(UnknownObject);

  short disconnectComponent(in string componentName,
														in string message,
														in string objName)
		raises(UnknownObject);

  oneway void sendBuffer(in log_msg_buf_t buffer,
												 in string objName);

  string getHostnameOf(in string componentName, in string objName)
		raises(UnknownObject);

  oneway void ping(in string componentName, in string objName);

  oneway void synchronize(in string componentName,
													in log_time_t componentTime,
													in string objName);
};
#endif
