/****************************************************************************/
/* DIET master agent IDL description                                        */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Sylvain DAHAN (Sylvain.Dahan@lifc.univ-fcomte.fr)                   */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$
 * $Log$
 * Revision 1.3  2004/09/29 13:35:31  sdahan
 * Add the Multi-MAs feature.
 *
 * Revision 1.2  2004/02/27 10:19:50  bdelfabr
 * description of all methods for data persistency
 *
 * Revision 1.1  2003/04/10 12:31:10  pcombes
 * Replace masterAgent.idl. submit returns only a response.
 *
 ****************************************************************************/

#ifndef _MASTER_AGENT_IDL_
#define _MASTER_AGENT_IDL_

#include "Agent.idl"


interface MasterAgent : Agent {
  
  /** Submission function: called by the clients to submit a problem. */
  corba_response_t submit(in corba_pb_desc_t pb_profile,
			  in unsigned long maxServers);
  
  /** get number of the current session */
  long get_session_num();

  /** get id of the data :  aggregation of numsession and numdata */
  string get_data_id();

  /** look up of data identified by id */ 
  unsigned long dataLookUp(in string id);

  /** get data descriptor */
  corba_data_desc_t get_data_arg(in string argID);

  /**
   * invoked by client : removal from the platform of the data identified by argID
   */
  long diet_free_pdata(in string argID);

#ifdef HAVE_MULTI_MA
  
  /** MAs federation management */
  boolean handShake(in MasterAgent me, in string myName);

  /** returns the address of the MA's bind service */
  string getBindName();

  /**
   * send a new request to the MA.
   */
  oneway void searchService(in MasterAgent me,
			    in string myName,
			    in corba_request_t request) ;

  /** ask to the MA to stop the flooding */
  oneway void stopFlooding(in long reqId, in string senderId) ;

  /** response which saids that the service is not found and a new step
      of flooding can be achive */
  oneway void serviceNotFound(in long reqId, in string senderId) ;

  /** launchs a new step of flooding */
  oneway void newFlood(in long reqId, in string senderId) ;

  /** response which saids that no new server can be found via this MA. */
  oneway void floodedArea(in long reqId, in string senderId) ;

  /** response which saids that the MA was already contacted for this
      request. */
  oneway void alreadyContacted(in long reqId,
			       in string senderId) ;

  /** response which saids that some servers was found. */
  oneway void serviceFound(in long reqId, in corba_response_t decision) ;

#endif // HAVE_MULTI_MA

};

#endif // _MASTER_AGENT_IDL_
