/****************************************************************************/
/* Workflow monitoring interface                                            */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Abdelkader Amar (Abdelkader.Amar@ens-lyon.fr)                       */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$
 * $Log$
 * Revision 1.8  2010/07/20 08:56:23  bisnard
 * Updated WfLogService IDL
 *
 * Revision 1.7  2009/06/23 09:16:19  bisnard
 * changed CORBA class name WfLogSrv to match DIET_Dashboard
 *
 * Revision 1.1  2008/04/10 08:17:14  bisnard
 * New version of the MaDag where workflow node execution is triggered by the MaDag agent and done by a new CORBA object CltWfMgr located in the client
 *
 * Revision 1.4  2006/11/28 15:17:54  aamar
 * Remove a space\!
 *
 * Revision 1.3  2006/11/28 15:14:47  aamar
 * Correct headers
 *
 * Revision 1.2  2006/11/28 15:10:18  aamar
 * Correct headers
 *
 ****************************************************************************/

#ifndef _WFLOGSERVICE_IDL_
#define _WFLOGSERVICE_IDL_

interface WfLogService {

  oneway void
  initWorkflow(in string wfId, in string name, in string parentWfId);

  void
  updateWorkflow(in string wfId, in string wfState, in string data);

  void
  createDag(in string dagId, in string wfId);

  void
  updateDag(in string dagId, in string wfId, in string dagState, in string data);
  
  void
  createDagNode(in string dagNodeId, in string dagId, in string wfId);

  void
  createDagNodePort(in string dagNodePortId, in string portDirection,
		    in string dagNodeId, in string wfId);

  void
  setInPortDependencies(in string dagNodePortId, in string dagNodeId, in string wfId,
                        in string dependencies);
  
  void
  createDagNodeLink(in string srcNodeId, in string srcWfId,
		    in string destNodeId, in string destWfId);
		    
  void
  createDagNodeData(in string dagNodeId, in string wfId,
		    in string dagNodePortId, in string dataId);

  void
  createDataElements(in string dataId, in string elementIdList);

  void
  createSourceDataTree(in string sourceId, in string wfId, in string dataIdTree);

  void
  createSinkData(in string sinkId, in string wfId, in string dataId);

  void
  nodeIsReady(in string dagNodeId, in string wfId);

  void
  nodeIsStarting(in string dagNodeId, in string wfId, in string pbName, in string hostname);
		    
  void
  nodeIsRunning(in string dagNodeId, in string wfId);

  void
  nodeIsDone(in string dagNodeId, in string wfId);

  void
  nodeIsFailed(in string dagNodeId, in string wfId);

};

#endif // _WFLOGSERVICE_IDL_
