#!/bin/bash

# This script launches a minimalistic omniNames server. It was "designed"
# as a small utility for lightweight troubleshooting. Hence it supposes
# an interactive usage and it expects to be roughly interupted with a
# good CTRL-C accross the head...
# You might want to change the invocation to something a bit more robust e.g.
#     nohup $OMNINAMES_CMD [...] &
# The requests should be executed on the NAMESERVICE_PORT (see below) port.

##### Things you might want to change:
# OmniOrb4 installation directory:
OMNIORB_PATH=$HOME/local/omniORB-4.0.7

# The name of the host of the service: usually this is a FQDN (Fully Qualified
# Domain Name)
SERVER_NAME=`hostname`"."`dnsdomainname`

# The primary port on which omniMapper listens fo IIOP requests. This is
# usually defaulted to 2809. We default it to 20809 to avoid a port bind
# rejection with a potential system owned server:
MAPPER_PORT=20809

# The port on which NameService will be available:
NAMESERVICE_PORT=20810

# Loging related:
export OMNINAMES_LOGDIR=`pwd`
  LOG_FILENAME=$OMNINAMES_LOGDIR/OmniNames.out
ERROR_FILENAME=$OMNINAMES_LOGDIR/OmniNames.err
# The following are generated by omniNames when using the start option:
 OMNINAMES_LOG=$OMNINAMES_LOGDIR/omninames-`hostname`.log
 OMNINAMES_BAK=$OMNINAMES_LOGDIR/omninames-`hostname`.bak

# Remove command:
REMOVE_CMD="/bin/rm -f"

############################################################
export LD_LIBRARY_PATH=$OMNIORB_PATH/lib
export OMNINAMES_CMD=$OMNIORB_PATH/bin/omniNames

$REMOVE_CMD $LOG_FILENAME $ERROR_FILENAME $OMNINAMES_LOG $OMNINAMES_BAK
$OMNINAMES_CMD -start $MAPPER_PORT -ignoreport  \
  -ORBInitRef NameService=corbaname::$SERVER_NAME:$NAMESERVICE_PORT \
  -ORBendPoint giop:tcp:$SERVER_NAME:$NAMESERVICE_PORT \
  -ORBsupportBootstrapAgent 1  \
  > $LOG_FILENAME 2> $ERROR_FILENAME

